language: node_js
node_js:
  - "0.10"
env:
  global:

after_success:
    "curl --ftp-create-dirs -T TRAVIS_BUILD_DIR/Gruntfile.js -u secure: E6re0Ttj35AGh5wiQ+pqk+2/AIhVQKuo/Apmgvwyb9dAAUGmanG/j1RJfdNBwhWKynOFac01qaBI2MHzQiF0QQfhd+Z/yqQXnxVmbCVF4vEK1QdPO+NPYYJ+sLqbUCiSZy3RvOTToaZZD4dUchFmlWZ9PULWVqSl2HP4HjnNW6k=:secure: KSBwuUQpfyn4v8aDV2fWlo+UF3tCL9IMGpPy+pgu7rBRAJP/wHzeqyxCF/ZWJnqtWHSqgiqnbsEzB6xfpqi1toRcVHizriletNexHlPZB3fXQtHFAs7wRu3hthWp8lJT6FfvU+L+6GIA4nEbsIxHvSaB/AT77av/K0C632X1F2o= ftp:secure: Uc/sC33XU/c5huxpQdM44G7CGwZAXqCU1MRKY8Ijy5GDXfR35fDPPOy/7ka3RI3Kz42Tw9iy+t6HrmuQS7Yvs67NGIZc/BNhXEfxxIOz4vvdMFI2nZN3C8HomM5Mz0iWhDumoOHyNZQ//g0cL0Kvay8DraRJeHp+r0bD8LHyPZc="

notifications:
  email:
    recipients:
      - trey.eckels@gmail.com
      - Ben@disasteraccountability.org